const amIEligibleLocations = [
  '**Washington Avenue Armory - Albany, Schenectady, Troy',
  'Washington Avenue Armory - Albany, Schenectady, Troy',
  'Washington Avenue Armory',
  'SUNY Albany',
  'SUNY Corning Community College',
  'Rochester Dome Arena',
  'SUNY Binghamton',
  'SUNY Orange',
  'Javits Center',
  'SUNY Oneonta',
  'Plattsburgh International Airport',
  'SUNY Potsdam',
  'Queensbury Aviation Mall - Sears',
  'Queensbury Aviation Mall',
  '**Former Kodak Hawkeye Parking Lot - Rochester',
  'Former Kodak Hawkeye Parking Lot - Rochester',
  'Former Kodak Hawkeye Parking Lot',
  'State Fair Expo Center: NYS Fairgrounds',
  'State Fair Expo Center',
  'SUNY Polytechnic Institute',
  'Westchester County Center',
  'Suffolk CCC - Brentwood',
  'Suffolk CCC',
  'Bronx - Bay Eden Senior Center',
  'Bay Eden Senior Center',
  '**Medgar Evers College - Brooklyn',
  'Medgar Evers College - Brooklyn',
  'Medgar Evers College',
  '**Delavan Grider Community Center - Buffalo',
  'Delavan Grider Community Center - Buffalo',
  'Delavan Grider Community Center',
  'University at Buffalo South Campus',
  'SUNY Old Westbury',
  '**York College - Health and Physical Education Complex - Queens',
  'York College - Health and Physical Education Complex - Queens',
  'York College - Health and Physical Education Complex',
  'York College',
  'Ulster Fairgrounds in New Paltz',
  'Ulster Fairgrounds',
  'Javits Center',
  'The Conference Center Niagara Falls',
  'Queensbury Aviation Mall - Sears',
  'Queensbury Aviation Mall',
  'Aqueduct Racetrack',
  'Stony Brook - Southampton',
  'Stony Brook',
  'SUNY Stony Brook',
  'SUNY Rockland Community College',
  'Jones Beach - Field 3',
  'Jones Beach',
  '**New York National Guard Armory - Yonkers and Mount Vernon',
  'New York National Guard Armory - Yonkers and Mount Vernon',
  'New York National Guard Armory',
];

module.exports = amIEligibleLocations;
