const vax4nycLocations = [
  'Co-Op City Dreiser Community Center',
  'Bronx Co-Op City Dreiser Community Center',
  'Bronx High School of Science',
  'Bathgate Contract Postal Station',
  'South Bronx Educational Campus',
  'Morrisania Health Center',
  'West Bronx Gymnasium',
  'Abraham Lincoln High School',
  'Bushwick Educational Campus',
  'Canarsie High School',
  'Teachers Preparatory High School',
  'Brooklyn Army Terminal',
  'Bed-Stuy Restoration',
  'Ezra Medical Center',
  'Spring Creek Towers',
  'Cityblock Health',
  'Fort Greene Health Center',
  'The NYPD Community Center',
  'Crown Heights Health Center',
  'Church of God of East NY',
  'Flatbush YMCA',
  'BMS Covid-19 Vaccination at St Paul Community BC',
  'City Point',
  'BMS Covid-19 Vaccination at St Paul Community BC',
  'City College of New York North Academic Center',
  'East Harlem Action Health Center',
  'Essex Crossing',
  'Ford Foundation',
  'Hospital for Special Surgery',
  "NYC Administration for Children's Services",
  'Convent Avenue Baptist Church',
  'Abyssinian Baptist Church',
  'August Martin High School',
  'Long Island City - 46th Road',
  'Beach Channel Educational Campus',
  'Hillcrest High School',
  'Martin Van Buren High School',
  'Citi Field',
  'Elmhurst/Newtown High School',
  'Corona Health Center',
  'Rikers Island Correctional Facility',
  'NYC Department of Health Gotham Center',
  'Flushing Library',
  'Korean Community Services',
  'New Jerusalem Worship Center',
  'Empire Outlets',
  'Port Richmond High School',
  'Ocean Breeze Athletic Complex',
  'Susan Wagner High School',
];

module.exports = vax4nycLocations;
